modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "gtmplusplus"
version = "${version}"
displayName = "GTM++"
authors = "Darmstadtium271"
description = ''''''
#logoFile = ""

[[dependencies.gtmplusplus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtmplusplus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gtmplusplus]]
modId = "gtceu"
mandatory = true
versionRange = "[1.7.0,)"
side = "BOTH"

