name: Build on Push

on:
  push:

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build --scan
      - name: Upload JAR File
        uses: actions/upload-artifact@v4
        with:
          name: GTMPlusPlus
          path: ./build/libs